name: pokedex
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  flutter_bloc: ^8.0.1
  json_annotation: ^4.4.0
  freezed_annotation: ^1.1.0
  hive: ^2.1.0
  cupertino_icons: ^1.0.2
  extended_image: ^6.0.2+1
  shimmer: ^2.0.0
  path_provider: ^2.0.9
  get_it: ^7.2.0
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  build_runner: ^2.1.8
  json_serializable: ^6.1.5
  flutter_svg: ^1.0.3
  badges: ^2.0.2
  tab_indicator_styler: ^2.0.0
  flutter_launcher_icons: ^0.9.2
  lint: ^1.5.3

  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launcher_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
